### ISSUE TITLE
what can be done for unbalanced data?

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pyARC#10]
what can be done for unbalanced data?
let say 90% of labels is no and 10% of data is yes

**Comment by kliegr** [comment]
In this case, you need to make sure to lower the support threshold so that you get rules covering the less frequent class. Other than that CBA could be quite resistant to favouring the majority class, since the first criterion for finding a matching rule is the confidence of the rule, rather than rule support (which corresponds to number of covered instances).

**Comment by Sandy4321** [comment]
Great thanks for soon answer,
Only to just make clear ,
What you mean under 
confidence of the rule
Is it ratio of correctly classified by this rule to wrongly classified by this rule?

**Comment by Sandy4321** [comment]
Do I understand correctly
If there is 99% of labels are no and 1% of labels are yes
Then this obvious rule :  all observation are levelled by no will not be used
In another words this code will provide high value of F1 metric for unbalanced data

**Comment by kliegr** [comment]
Not really, please refer to here: https://en.wikipedia.org/wiki/Association_rule_learning#Confidence

**Comment by jirifilip** [comment]
Additionally, you can set minimum support and confidence thresholds when creating a CBA object

```python
cba = CBA(support=0.20, confidence=0.5)
```
